// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrjwrbbngvxlvcczxxss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyandyYmJuZ3Z4bHZjY3p4eHNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MDc5NjcsImV4cCI6MjA2NDE4Mzk2N30.HbGHPVPmqHRpe-Pifsy9Vsando8qhV4XvsVC0gArAU4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);